### ISSUE TITLE
Questions about your guide of BNN for MNIST and CIFAR10

### ISSUE THREAD

**Issue by yuanchunyu** [larq/larq#611] opened 2021-01-15 05:32 UTC
I have questions about the two guides of "https://docs.larq.dev/larq/tutorials/binarynet_cifar10/" and "https://docs.larq.dev/larq/tutorials/mnist/".

Why do you need to do this step("# Normalize pixel values to be between -1 and 1") before training? This step will let all of your input became binary(+1 and -1) before entering into the network.

**Comment by jneeven** [comment] 2021-01-15 08:39
Hello! The inputs will be in range (-1, 1), but they will be floats, so the images won't have binary (either -1 or 1) values, but a range of 256 float values between -1 and 1. This is a very common normalization method, not specific to BNNs, which helps stabilize training. The first layer in the BinaryNet network doesn't have an input quantizer, so the activations are only binarized later in the network. Let me know if you have any further questions!

**Comment by rameshKrSah** [comment] 2021-06-09 03:45
For the MNIST example, training on CPU maximum accuracy reached after 100 was around 38% but training on GPU the accuracy was 97% after only 6 epoch. Why is this difference between training on GPU and without a GPU? I don't understand it.

**Comment by jneeven** [comment] 2021-06-09 07:26
@rameshKrSah that sounds like a bug, but I can't reproduce it. If I run the MNIST [colab notebook](https://colab.research.google.com/github/larq/docs/blob/master/docs/larq/tutorials/mnist.ipynb) with hardware accelerator `None`, I still get 96% accuracy. Perhaps you've accidentally changed something else?
![image](https://user-images.githubusercontent.com/19648598/121311449-b776cb00-c904-11eb-8909-f4185ede2224.png)

**Comment by rameshKrSah** [comment] 2021-06-09 16:49
@jneeven oh yeah, I must have some bug. Now it is the same on both CPU and GPU. Thanks!

**Closed** 2021-06-09 17:53 UTC
